tb1337/paperless-api

- README.md
- pypaperless/auth.py
- pypaperless/model.py
- pypaperless/paperless.py
Hi @tb1337 
I have added support in your Paperless API for requesting single items (documents, tags, etc.) as well as posting new PDF documents, and searching for documents in Paperless. 
Would be great if you integrate these changes.
Cheers
André
> Added support for single items, posting, and search  

- .github/workflows/pr-labels.yml
- pypaperless/__init__.py
- pypaperless/api/base.py
- pypaperless/api/documents.py
- pypaperless/api/tasks.py
- pypaperless/errors.py
- tests/conftest.py
- tests/pypaperless/test_consumption_templates.py
- tests/pypaperless/test_correspondents.py
- tests/pypaperless/test_custom_fields.py
- tests/pypaperless/test_document_types.py
- tests/pypaperless/test_documents.py
- tests/pypaperless/test_groups.py
- tests/pypaperless/test_mail_accounts.py
- tests/pypaperless/test_mail_rules.py
- tests/pypaperless/test_saved_views.py
- tests/pypaperless/test_storage_paths.py
- tests/pypaperless/test_tags.py
- tests/pypaperless/test_tasks.py
- tests/pypaperless/test_users.py
Split ```paperless.request()``` into three functions:
1. ```paperless.generate_request()```, which returns a ClientResponse object
2. ```paperless.request_json()```, which expects a json string and returns a dict
3. ```paperless.request_file()```, which returns the response content as bytes
That change enables developers to create raw requests by themselves, if needed.
Updated related tests, too.
Resolves #11.
> Add better request/response handling

- docs/SESSION.md
- pypaperless/__init__.py
- pypaperless/util.py
- pyproject.toml
- tests/api/test_general.py
- tests/conftest.py
There was a relic in the code from the beginning of the project, which should be solved now. PyPaperless now utilizes yarl, which was already a sub dependency.
Before merge, we have little more work:
* Update documentation
* ~~Update toml to add the yarl dependency~~
* Move new logic into a helper function (for tests)
Solves #49.
> Fix hardcoded http in url (#49)

- docs/CRUD.md
- pypaperless/controllers/base.py
- pypaperless/controllers/documents.py
- tests/test_paperless_0_0_0.py
- tests/test_paperless_1_17_0.py
- tests/test_paperless_1_8_0.py
- tests/test_paperless_2_0_0.py
- tests/test_paperless_2_3_0.py
- tests/util/router.py
Add custom fields service on the DocumentsController. The method accepts either a list of CustomFieldValues or empty list, and will persist that list on Paperless-ngx. Existing data gets overwritten.
Also added this fact to the documentation.
Resolves #54.
> Feature Request: maintain custom fields at a document

- tests/test_paperless_0_0_0.py
- tests/test_paperless_1_8_0.py
- tests/test_paperless_2_0_0.py
- tests/test_paperless_2_3_0.py
> Add missing tests

- pypaperless/models/mixins/models/updatable.py
- tests/test_paperless_0_0_0.py
Fix `set_permissions` on model update.
Resolves #95
> Fix `set_permissions` on model update

- pypaperless/models/utils/__init__.py
Resolves #113 
Datetime objects were serialized in a wrong format, so Paperless responded with a format error. This happened in timezones with a time delta >0.
> Fix date to str converison

- .devcontainer/devcontainer.json
- src/pypaperless/api.py
- src/pypaperless/exceptions.py
- tests/test_common.py
- tests/test_models_matrix.py
- tests/test_models_specific.py
Remove `noqa` flags and refactor code, fix security issues and code analysis alerts.
> Improve code quality

- src/pypaperless/api.py
- src/pypaperless/exceptions.py
- tests/test_common.py
pypaperless shall raise an InitializationError when got into trouble on initialization of the `Paperless` object.
It will raise when getting a HTTP error or when the first payload cannot json decoded, during initialization.
> Add initialization error

- src/pypaperless/models/mixins/helpers/callable.py
- src/pypaperless/models/mixins/helpers/iterable.py
- tests/test_models_matrix.py
`pypaperless` didn't request object permissions when using the IterableMixin, as it did when using the CallableMixin.
Solves #161.
> Fix permissions are not requested by pages()/reduce()

- src/pypaperless/api.py
The `aiohttp.FormData` default is to encode all parameter data on form fields, and this causes e.g. spaces to be converted to `%20`, which are then [exposed in the Paperless-NGX UI](https://github.com/paperless-ngx/paperless-ngx/issues/6830).
I interpret the [`aiohttp` issue](https://github.com/aio-libs/aiohttp/pull/6826) to mean that the filename should *not* be percent-encoded, and the [proposed solution](https://github.com/aio-libs/aiohttp/pull/6826#issuecomment-1184833636) is to set `quote_fields=False` in the constructor of `aiohttp.FormData`.
Which is what this PR does.
> Do not quote Multipart fields in forms

- src/pypaperless/models/common.py
Tasks that have been started can now be represented as TaskStatusType.STARTED, where previously they'd be rendered as UNKNOWN.
> Add Task status for STARTED

- src/pypaperless/models/mixins/helpers/iterable.py
For `__in` filters, the Paperless NGX API expects a comma-separated string of IDs, not a list (see
https://github.com/paperless-ngx/paperless-ngx/issues/6996). This patch turns a list into such a string for `__in` filters.
Closes: #226
> Turn `__in` filter lists into comma-separated strings

- .github/workflows/tests.yml
- poetry.lock
- pyproject.toml
- src/pypaperless/exceptions.py
- tests/test_common.py
In case of custom_fields errors, no meaningful error message was displayed. This PR will address this issue by adding a little recursive parser, as error payloads can be nested lists and dicts.
Will close #295
> Improve error message parsing

- pypaperless/models/common.py
- pypaperless/models/custom_fields.py
- pypaperless/models/utils/__init__.py
- pyproject.toml
- tests/test_common.py
I want to improve working with `CustomField.extra_data` but still handle it as a normal dict, as it isn't important enough to be a dataclass, but still needed especially when parsing custom_field data or creating new custom fields in Paperless-ngx.
* Make `extra_data` a TypedDict
* Add TypedDict handling to `dict_value_to_object` and `object_to_dict_value`
* Add tests
Closes #374
> Make `CustomField.extra_data` a typed dict

- pypaperless/api.py
I updated the way headers are handled to avoid the issue caused by trying to update a mappingproxy object. In Python, mappingproxy objects are immutable, meaning you cannot modify them directly using methods like update(). To resolve this, I switched to an approach where the headers are merged with custom ones or set to default headers, without trying to update the mappingproxy object directly.
This caused errors when passing in a custom session.
> removed header update on session

- pypaperless/api.py
- pypaperless/const.py
- pypaperless/helpers.py
- pypaperless/models/__init__.py
- pypaperless/models/remote_version.py
- tests/data/__init__.py
- tests/data/v0_0_0.py
- tests/test_models_specific.py
Added /api/remote_version endpoint.
I'm not sure when the endpoint was added, but it's been around for a while. I just put it under 0.0.0 for now.
Edit: I know the version is already in the status and api, but the endpoint isn’t protected and also returns whether an update is available. It could be used to check if paperless can be reached.
> Add remote version endpoint

- pypaperless/api.py
- pypaperless/exceptions.py
- tests/conftest.py
- tests/test_common.py
Hey! :)
Another PR from me. I’ve added improved error handling to check whether a user has given an invalid token or is inactive or deleted.
Both cases are based on the auth error, if the specific errors isn't needed.
Previously, depending on the case, I had BaseJsonResponseErrors or ClientErrors, which had to be interpreted individually with inner error.
> Add errors for bad authentication

- pypaperless/api.py
- tests/test_common.py
Hey, 
currently the trailing slash is only removed if no scheme is given.
We should remove the trailing slash generally.
So if a user enters https://yourdomain.com/ we also remove the slash.
> Remove trailing slash if no scheme given

- pypaperless/models/utils/__init__.py
fix parsing created date (fixes #482)
`date.fromisoformat()` expects YYYY-MM-HH, but in some processing step before a date like `2024-06-28T00:00:00+00:00` is generated, so this fails.
`datetime.time.fromisoformat('2024-06-28T00:00:00+00:00')` fails with
`ValueError: Invalid isoformat string: '2024-06-28T00:00:00+00:00'`.
Using `datetime.fromisoformat(datestr).date()` accepts a longer string and cuts it down to a date, e.g.
```
>>> datetime.datetime.fromisoformat('2024-06-28T00:00:00+00:00').date()
datetime.date(2024, 6, 28)
```
> fix parsing created date (fixes #482)
