.github/workflows/ci.yaml
.github/workflows/python-publish.yml
README.md
pypaperless/auth.py
pypaperless/model.py
pypaperless/paperless.py

hi,
1) use python black for code formatting
2) introduce simple github workflow to check formatting
3) add add_correspondent function to be able to add correspondents.

code formatting, add_correspondent

---

.github/dependabot.yml
.github/release-drafter.yml
.github/workflows/pr-labels.yml
.github/workflows/pre-commit-updater.yml
.github/workflows/release-drafter.yml
.github/workflows/release-package.yml
.github/workflows/test.yml
README.md
pypaperless/api.py
pypaperless/models/tasks.py
tests/fixtures/data.json
tests/pypaperless/test_consumption_templates.py
tests/pypaperless/test_correspondents.py
tests/pypaperless/test_custom_fields.py
tests/pypaperless/test_document_types.py
tests/pypaperless/test_documents.py
tests/pypaperless/test_groups.py
tests/pypaperless/test_mail_accounts.py
tests/pypaperless/test_mail_rules.py
tests/pypaperless/test_saved_views.py
tests/pypaperless/test_storage_paths.py
tests/pypaperless/test_tags.py
tests/pypaperless/test_tasks.py
tests/pypaperless/test_users.py

We plan to use that lib as a dependency for a Home Assistant integration. This PR merges the first big update, further enhancements will arrive soon.
Resolves #8.

Rewrite to async

---

.github/release-drafter.yml
pypaperless/__init__.py
pypaperless/api.py
pyproject.toml

Protected the logger property in sub classes.
Also updated the project files, refactors just raise the patch level like bugs.
Resolves #10.

Set logger protected

---

.github/release-drafter.yml

Add autolabeler to release drafter.

Add autolabeler to release drafter

---

.github/dependabot.yml
.github/workflows/release-package.yml
README.md

Update project files to add trusted publishing to PyPI and labels to dependabot pull requests.

Add trusted publishing and labels

---

pypaperless/api.py
tests/fixtures/data.json
tests/pypaperless/test_consumption_templates.py
tests/pypaperless/test_correspondents.py
tests/pypaperless/test_custom_fields.py
tests/pypaperless/test_document_types.py
tests/pypaperless/test_documents.py
tests/pypaperless/test_groups.py
tests/pypaperless/test_mail_accounts.py
tests/pypaperless/test_mail_rules.py
tests/pypaperless/test_saved_views.py
tests/pypaperless/test_storage_paths.py
tests/pypaperless/test_tags.py
tests/pypaperless/test_tasks.py
tests/pypaperless/test_users.py

Implemented more testing, especially for iteration methods. There are still tests missing for create/update/delete and sub endpoints (f.e. documents).

Add tests for iterate methods

---

pypaperless/__init__.py
pypaperless/api/base.py
pypaperless/api/documents.py
tests/pypaperless/test_tasks.py

Also added ```last_page``` for PaginatedResults.
Resolves #27.

Increase page_size for paginated requests

---

docs/CRUD.md

Document note crud is now documented.

Add documentation for document notes

---

.github/workflows/test.yml
pyproject.toml

Add urls to pyproject.toml and codecov upload.

Update project files

---

.github/workflows/test.yml

Add cov report and xml convert

---

.codecov.yml
README.md

Doing some project file related stuff.

Update coverage configs

---

.codecov.yml
pypaperless/api/documents.py
tests/api/__init__.py
tests/api/test_documents.py
tests/common/__init__.py
tests/common/test_stuff.py
tests/fixtures/data.json

Add tests for sub-endpoints, resolve #21.
Add tests for uncovered code segments.

Add more tests

---

pypaperless/__init__.py
pypaperless/api/base.py
pypaperless/api/documents.py
pypaperless/api/tasks.py
pypaperless/models/base.py
pypaperless/models/documents.py
pypaperless/models/shared.py
pypaperless/util.py
pyproject.toml

Add more typing

---

.devcontainer/devcontainer.json
Dockerfile
script/bootstrap
script/setup

Move dev environment into devcontainer for easier sharing it.

Add devcontainer

---

poetry.lock
src/pypaperless/models/documents.py

Some ruff rules changed, so this directive was no longer necessary.

Remove unused noqa directive

---

src/pypaperless/models/classifiers.py

Remove text_color from TagDraft required_fields

---

.github/workflows/tests.yml

Disable sonarcloud in pipeline

---

pypaperless/api.py
pypaperless/const.py
pypaperless/helpers.py
pypaperless/models/__init__.py
pypaperless/models/common.py
pypaperless/models/share_links.py
pypaperless/models/statistics.py
tests/data/__init__.py
tests/data/v2_15_0.py
tests/test_models_specific.py

Add statistics api endpoint

---

pypaperless/models/common.py

Add missing fields and statustype value
Paperless-Version 2.15.3

Add missing fields and statustype to status endpoint

---

.github/workflows/linting.yml
.github/workflows/tests.yml
.github/workflows/typing.yml

Actions shall only run on pull requests.

Remove github actions on push

---

pypaperless/api.py
pypaperless/models/base.py
pypaperless/models/classifiers.py
pypaperless/models/config.py
pypaperless/models/custom_fields.py
pypaperless/models/documents.py
pypaperless/models/mails.py
pypaperless/models/permissions.py
pypaperless/models/remote_version.py
pypaperless/models/saved_views.py
pypaperless/models/share_links.py
pypaperless/models/statistics.py
pypaperless/models/status.py
pypaperless/models/tasks.py
pypaperless/models/workflows.py
tests/test_common.py

Remove remote endpoint checking

---

pypaperless/const.py

Raise api version
